### ISSUE TITLE
problem on docker

### ISSUE THREAD

**Issue by acforce** [shuohangwang/SeqMatchSeq#10]
When I run it through docker, it stuck at here:
[................... 1/87599 ..................] ETA: 0ms | Step: 0ms

**Comment by shuohangwang** [comment]
Thank you for the interest in this project!

May I know your docker version and the command to run the code?

**Comment by acforce** [comment]
I run on both Windows and Mac. Both of their docker are version 18.03.0.
The command is exactly the commands in Readme, with only the PATH is different.

**Comment by shuohangwang** [comment]
I just test it on Mac with the latest stable docker. It's ok for me.

I think it might be "out of memory" issue, as I used multiple CPU threads to run the code.

Could try to modify the hyper-parameter file "init.lua" as follows, then rerun the code?
opt.batch_size = 2
opt.num_processes = 2
opt.mem_dim = 10
opt.att_dim = 10

Please let me know if it still doesn't work! 

If it works, you may set a larger value for these parameters.  

Thanks!
