### ISSUE TITLE
About Machine Comprehension Using Match-LSTM and Answer Pointer

### ISSUE THREAD

**Issue by siddalmia** [shuohangwang/SeqMatchSeq#7]
Hi,

I have a concern regarding my reimplementation of the "Machine Comprehension Using Match-LSTM and Answer Pointer".

1. Are the LSTM parameters in the Match-LSTM in the forward and backward direction shared?
2. Also from your code I understand that the Passage and Question preprocessing LSTM have shared weights, is this correct? 

Thanks in advance!

**Comment by shuohangwang** [comment]
Thank you for the interest in our work!

Yes, both 1 and 2 are shared in my implementation! 

BTW, for 1, the parameters of attention mechanism in both directions are also shared.

Best,
Shuohang
