### ISSUE TITLE
Match LSTM prediction.json

### ISSUE THREAD

**Issue by waheedabro** [shuohangwang/SeqMatchSeq#8]
Hello, I'm new to machine reading i read your awesome papers and tons of thanks for this repo. Currently i am running match LSTM "th mainDt.lua" and facing below problem. 

FileNotFoundError: [Errno 2] No such file or directory: '../trainedmodel/evaluation/squad/prediction.json'.

I don't have idea from where i can get this prediction.json file.

Thanks for your time.

**Comment by shuohangwang** [comment]
Hi, thank you for the interest in our work!

This file is generated by this line "sys.execute('python ../trainedmodel/evaluation/squad/txt2js.py ../data/squad/dev-v1.1.json ../trainedmodel/evaluation/squad/dev_output.txt ../trainedmodel/evaluation/squad/prediction.json')".

Could you try the Docker I provided? Maybe you miss some packages.

Thank you!

**Comment by waheedabro** [comment]
Thank you so much for your prompt response. Due to my working environment below two line in txt2js.py was creating problem i have commented below lines. Its working good.
reload(sys)
sys.setdefaultencoding('utf-8') 

Thanks again for your time and help.
